### ISSUE TITLE
[Question] It is recommended to modify the support for .NET Framework 4.6.1 and upgrade the supported version of ASP.NET Core

### ISSUE THREAD

**Issue by stulzq** [apache/shenyu-client-dotnet#23]
### Question

ASP.NET Core >= 5 no longer supports .NET Framework, Only run .NET Core. The new ASP.NET Core brings many feature changes, especially 3.1->5.0, if the multi-target framework is used to support it, it will complicate the code and increase the maintenance cost, and ASP.NET Core <= 3.1 is already an older version.

If you want to support .NET Framework I recommend maintaining a separate project (Library)

Then upgrade the supported version of the class library to .NET 5.0, 6.0

I can get the job done if the suggestion is taken.

**Comment by hgaol** [comment]
Hi @stulzq , thanks for your suggestion! I plan to use `client` project as a common low layer lib project, and provide `asp.net.core` and `asp.net` project (which not implemented yet) which based on it.
For `asp.net.core`,  it will support asp.net core 3, 5 and 6. For `asp.net` which is aim to support the .net framework project. I think they're not conflict. What's your opinion?
