### ISSUE TITLE
代理接口访问不到

### ISSUE THREAD

**Issue by bingtianyiyan** [apache/shenyu-client-dotnet#30]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

netcore程序已经注册进shenyu，界面上已经显示。使用postman请求代理接口不通。本地启动是可以用本机ip或者localhost访问接口， 不通过代理访问接口。当初以为是docker容器没开放访问本机权限，下载java程序到本地启动，netcore程序改成访问本地java程序，正常注册进shenyu，不过再次尝试使用postman请求代理接口不通

### Expected Behavior

能够访问代理后的接口，想请问下是设置问题还是操作不当引起

### Environment

```markdown
ShenYu version(s):最新master分支
```

### Debug logs

现象：接口http://127.0.0.1:9195/dotnet2/template/hello 访问不通

shenyu界面：
<img width="871" alt="1660105948(1)" src="https://user-images.githubusercontent.com/48984656/183816450-3d6369fc-bf36-4199-a49e-9fa27bd993bc.png">

netcore启动：localhost和本机ip都是可以正常直接访问相应接口
netcore配置：
 "Shenyu": {
    "Register": {
      "ServerList": "http://127.0.0.1:9095",
      "RegisterType": "http",
      "Props": {
        "UserName": "admin",
        "Password": "123456"
      }
    },
    "Client": {
      "AppName": "dotnet-example2",
      "ContextPath": "/dotnet2",
      "IsFull": false,
      "ClientType": "http"
    }
  }

java程序：
<img width="908" alt="1660105981(1)" src="https://user-images.githubusercontent.com/48984656/183816499-385d0d5a-ead0-4d0f-afb2-1bd236a175ae.png">

**Comment by bingtianyiyan** [comment]
<img width="728" alt="1660106156(1)" src="https://user-images.githubusercontent.com/48984656/183816785-752ea98f-6135-4cc2-9ab6-d49a4f5ddc1f.png">

**Comment by bingtianyiyan** [comment]
<img width="921" alt="1660106331(1)" src="https://user-images.githubusercontent.com/48984656/183817106-a33648c0-2747-446e-8cc6-167e5d66c2a3.png">
<img width="925" alt="1660106404(1)" src="https://user-images.githubusercontent.com/48984656/183817230-32597913-1114-468f-a8f6-89ddc2af985e.png">

**Comment by hgaol** [comment]
Can you use English instead of Chinese?

For your question, did you start the `bootstrap` as gateway? And share the response of it?

**Comment by bingtianyiyan** [comment]
来信已收到，我会尽快回复，杨

**Comment by bingtianyiyan** [comment]
I am a reference this pape https://shenyu.apache.org/zh/docs/deployment/deployment-local to start local bootstrap。
then run shenyu-client-dotnet sample.
I has question you say start the bootstrap as gateway??  the shenyu-admin start org.apache.shenyu.bootstrap.ShenyuBootstrapApplication should set as gateway mode? I
not see any document  write where to set，Is not the program itself can be started as a gateway？
shenyu-admin-ui I have check pluge is all open

**Comment by bingtianyiyan** [comment]
I'm very sorry, I should know the reason, I started the admin program, but did not start again another program org. Apache. Shenyu. The bootstrap. ShenyuBootstrapApplication

**Comment by bingtianyiyan** [comment]
now I start the bootstrap,can access to 9195,but
and use postman tools :http://127.0.0.1:9195/dotnet/template/hello
whether you hava meet this proble,i find the source is make shenyu-spi method createExtension
[problems.txt](https://github.com/apache/shenyu-client-dotnet/files/9313856/problems.txt)

**Comment by hgaol** [comment]
Maybe there's something wrong with `admin` or `bootstrap`, it's out of client's scope. After registered into admin, client finished his responsibility. And `admin` will sync with `bootstrap` about the selectors/rules information.

Did you change the configuration of `admin` or `bootstrap`? They should work well without any change of configurations.

Can you go to the admin portal to see if the instance is open or close in selector part?

Can you show the rules of `dotnet`? I saw your `dotnet2` rules seems with wrong path, here's mine. And I can call from gateway successfully.
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/11908658/184295466-a107fb77-802c-4983-a37f-dc426149116b.png">

**Comment by bingtianyiyan** [comment]
> Maybe there's something wrong with `admin` or `bootstrap`, it's out of client's scope. After registered into admin, client finished his responsibility. And `admin` will sync with `bootstrap` about the selectors/rules information.
> 
> Did you change the configuration of `admin` or `bootstrap`? They should work well without any change of configurations.
> 
> Can you go to the admin portal to see if the instance is open or close in selector part?

I Know  is not client responsibility,I not change configuration,only change database connecting, then to start project.
3q so much for you help~~~

**Comment by hgaol** [comment]
Can you pls to show the screenshot of the `dotnet` selector? Like what I pasted above. Any different?

**Comment by bingtianyiyan** [comment]
> Can you pls to show the screenshot of the `dotnet` selector? Like what I pasted above.

dotnet2 is yesterday i change contextPath,maby is me where set wrong 
now i retry  init database,interface retrun :{
  "code": -102,
  "message": "divide:Rule not found!",
  "data": null
}
but divide.Rule  in admin-ui i can find
so sad with ~~
<img width="944" alt="微信图片_20220812143842" src="https://user-images.githubusercontent.com/48984656/184299048-e768fd60-ab24-45a5-a3a2-0be807897c28.png">

**Comment by bingtianyiyan** [comment]
it is success now , i change the /dotnet/template\hello to /dotnet/template/hello like you show.
but project register is /dotnet/template\hello
<img width="580" alt="1660287068(1)" src="https://user-images.githubusercontent.com/48984656/184300236-e3be1420-a01e-4d2d-b4ca-6bdc7df662c8.png">

**Comment by hgaol** [comment]
It's strange and may be a bug. What's your operation system? And If it's truly a bug, do you have interests to fix it?

**Comment by bingtianyiyan** [comment]
> It's strange and may be a bug. What's your operation system? And If it's truly a bug, do you have interests to fix it?
win10~~
maybe is file ShenyuStartupService.cs 
 var wholePath = path == null ? basePath : Path.Combine("/", basePath, path);
this code shoud to windows ,the result is "path1\\\path2"
i think can replace method:var wholePath = path == null ? basePath : $"{basePath}/{path}";
<img width="387" alt="1660288982(1)" src="https://user-images.githubusercontent.com/48984656/184305187-64e7dc8d-de5d-476d-8af0-a56491ce5543.png">

**Comment by hgaol** [comment]
Fixed in #33 , close it.
